name: food_delivery
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - lib\assets\image1.png
  - lib\assets\image2.png
  - lib\assets\image3.png
  - lib\assets\google-plus 1.png
  - lib\assets\Rectangle 6.png
  - lib\assets\burger (1) 1.png
  - lib\assets\coffee-cup 1.png
  - lib\assets\potato-chips 1.png
  - lib\assets\piece-of-cake 1.png
  - lib\assets\Rectangle 6 (1).png
  - lib\assets\star.png
  - lib\assets\Ellipse 6.png
  - lib\assets\user 1.png
  - lib\assets\store 1 (1).png
  - lib\assets\shopping-list 1.png
 
