name: flutter_project_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/assets/images/hamburger1.png
  - lib/assets/images/facebook1.png
  - lib/assets/images/google-plus1.png
  - lib/assets/images/image1.png
  - lib/assets/images/image2.png
  - lib/assets/images/image3.png
  - lib/assets/images/food.png
  - lib/assets/images/girl1.png

  