name: project_two
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/resturant.png
    - assets/images/pizzas.png 
    - assets/images/hamburger.png
    - assets/images/burgers.png
    - assets/images/bbq.png
    - assets/images/profile_picture.png
    - assets/icons/burger.png  
    - assets/icons/clock.png
    - assets/icons/coffee-cup.png
    - assets/icons/dislike.png
    - assets/icons/like.png
    - assets/icons/person.png
    - assets/icons/piece-of-cake.png
    - assets/icons/pin.png
    - assets/icons/potato-chips.png
    - assets/icons/store.png
    - assets/icons/shopping_list .png
