name: project2_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\hamburger.png
    - assets\images\back.png
    - assets\images\burger.png
    - assets\images\pizza.png
    - assets\images\bbq.png
    - assets\images\potato-chips.png
    - assets\images\piece-of-cake.png
    - assets\images\coffee-cup.png
    - assets\images\burgerWhite.png
    - assets\images\facebook.png
    - assets\images\google-plus.png
    - assets\images\food.png
    - assets\images\like.png
    - assets\images\deslike.png
    - assets\images\profile.png
    - assets\images\order.png
    - assets\images\home.png
    - assets\images\pictureProfile.png

